/**
 * @author Nadir
 * @version 1.0
 */

const AUTH_STACK = 'AUTHENTICATION';
const LOGIN = 'LOGIN';
const SIGNUP = 'SIGNUP';
const ENTER_AS_GUEST = 'ENTER_AS_GUEST';
const SPLASH_SCREEN = 'SPLASH_SCREEN';
const SET_NEW_PASSWORD='SET_NEW_PASSWORD'

//Registered Muslim
const REGISTERED_MUSLIM_HOME_STACK = 'REGISTERED_MUSLIM_HOME';
const REGISTERED_MUSLIM_DASHBOARD_STACK = 'REGISTERED_MUSLIM_DASHBOARD_STACK';
const RECITE_QURAN = 'RECITE_QURAN';
const SURAH_RECITATION_AREA = 'SURAH_RECITATION_AREA';
const PARAH_RECITATION_AREA = 'PARAH_RECITATION_AREA';
const FIND_MOSQUE = 'FIND_MOSQUE';
const VIEW_CALANDER = 'VIEW_CALANDER';
const LEARN_NAMAZ = 'LEARN_NAMAZ';
const NAMAZ_PLAY_AREA = 'NAMAZ_PLAY_AREA';
const MUSLIM_USER_ANNOUNCEMENT_DETAILS='MUSLIM_USER_ANNOUNCEMENT_DETAILS'
const NO_CONNECTION_SCREEN='NO_CONNECTION_SCREEN'

const ACCOUNTABILITY = 'ACCOUNTABILITY';
const MUSLIM_ANNOUNCEMENTS = 'MUSLIM_ANNOUNCEMENTS';
const AUTO_SILENT = 'AUTO_SILENT';
const ADD_MOSQUE = 'ADD_MOSQUE';
const TASBIH_COUNTER = 'TASBIH_COUNTER';
const QIBLA_DIRECTION = 'QIBLA_DIRECTION';
const RAKAH_INFO = 'RAKAH_INFO';
const MAKE_ANNOUNCEMENT_SCREEN='MAKE_ANNOUNCEMENT_SCREEN'
const MUSLIM_VIEW_PROFILE='MUSLIM_VIEW_PROFILE'
const APPLY_AS_IMAM='APPLY_AS_IMAM'
const SHARE_APP='SHARE_APP'
const ABOUT='ABOUT'
const GOOGLE_MAP='GOOGLE_MAP'
const GOOGLE_MAP_DIRECTIONS='GOOGLE_MAP_DIRECTIONS'
const MUSLIM_DUAS='MUSLIM_DUAS'
const ALLAH_99_NAME='ALLAH_99_NAME'

const IMAM_CONSENSUS='IMAM_CONSENSUS'
const MOSQUE_CONSENSUS='MOSQUE_CONSENSUS'
const NEW_MOSQUE_ADDITION='NEW_MOSQUE_ADDITION'
const NAMAZ_ALERT_NOTIFICATION='NAMAZ_ALERT_NOTIFICATION'


//Registered Hindu
const REGISTERED_HINDU_HOME_STACK = 'REGISTERED_HINDU_HOME';
const REGISTERED_HINDU_DASHBOARD_STACK = 'REGISTERED_HINDU_DASHBOARD_STACK';

const RECITE_GITA = 'RECITE_GITA';
const FIND_TEMPLE = 'FIND_TEMPLE';
const VEG_DAYS = 'VEG_DAYS';
const VIEW_HINDU_CALANDER = 'VIEW_HINDU_CALANDER';
const HINDU_ANNOUNCEMENTS = 'HINDU_ANNOUNCEMENTS';
const HINDU_AUTO_SILENT = 'HINDU_AUTO_SILENT';
const ADD_TEMPLE = 'ADD_TEMPLE';

const GUEST_MUSLIM_HOME_STACK = 'Auth';
const IMAM_HOME_STACK = 'Auth';
const GUEST_HINDU_HOME_STACK = 'Auth';
const OTP_VERIFICATION = 'OTP_VERIFICATION';

//General User navigation constants
const HELP='HELP'

//Tab Navigation
const MUSLIM_SETTINGS="Settings"
const MUSLIM_HOME="Home"
const MUSLIM_ALERTS="Alerts"
const MUSLIM_PRAYERS="Prayers"

export{
  MUSLIM_ALERTS,
  MUSLIM_HOME,
  MUSLIM_SETTINGS,
  MUSLIM_PRAYERS
}

export {
  AUTH_STACK,
  SIGNUP,
  LOGIN,
  ENTER_AS_GUEST,
  OTP_VERIFICATION,
  SPLASH_SCREEN,
};

//Registered Muslim navigation constants
export {
  REGISTERED_MUSLIM_HOME_STACK,
  REGISTERED_MUSLIM_DASHBOARD_STACK,
  RECITE_QURAN,
  SURAH_RECITATION_AREA,
  PARAH_RECITATION_AREA,
  VIEW_CALANDER,
  FIND_MOSQUE,
  LEARN_NAMAZ,
  NAMAZ_PLAY_AREA,
  ACCOUNTABILITY,
  MUSLIM_ANNOUNCEMENTS,
  MAKE_ANNOUNCEMENT_SCREEN,
  MUSLIM_USER_ANNOUNCEMENT_DETAILS,
  AUTO_SILENT,
  ADD_MOSQUE,
  TASBIH_COUNTER,
  QIBLA_DIRECTION,
  RAKAH_INFO,
  MUSLIM_DUAS,
  ALLAH_99_NAME,
  MUSLIM_VIEW_PROFILE,
  APPLY_AS_IMAM,
  ABOUT,
  SHARE_APP,
  GOOGLE_MAP,
  GOOGLE_MAP_DIRECTIONS,
  IMAM_CONSENSUS,
  MOSQUE_CONSENSUS,
  NEW_MOSQUE_ADDITION,
  NAMAZ_ALERT_NOTIFICATION,
  NO_CONNECTION_SCREEN,
};

//Registered Hindu user navigation constants
export {
  REGISTERED_HINDU_HOME_STACK,
  REGISTERED_HINDU_DASHBOARD_STACK,
  RECITE_GITA,
  FIND_TEMPLE,
  VEG_DAYS,
  VIEW_HINDU_CALANDER,
  HINDU_ANNOUNCEMENTS,
  HINDU_AUTO_SILENT,
  ADD_TEMPLE,
  HELP
};
