/**
 * @author Nadir
 * @version 1.0
 */

const AUTH_STACK = 'AUTHENTICATION';
const LOGIN = 'LOGIN';
const SIGNUP = 'SIGNUP';
const ENTER_AS_GUEST = 'ENTER_AS_GUEST';

//Registered Muslim
const REGISTERED_MUSLIM_HOME_STACK = 'REGISTERED_MUSLIM_HOME';
const REGISTERED_MUSLIM_DASHBOARD_STACK = 'REGISTERED_MUSLIM_DASHBOARD_STACK';
const RECITE_QURAN = 'RECITE_QURAN';
const FIND_MOSQUE = 'FIND_QURAN';
const VIEW_CALANDER = 'VIEW_CALANDER';
const LEARN_NAMAZ = 'LEARN_NAMAZ';
const ACCOUNTABILITY = 'ACCOUNTABILITY';
const ANNOUNCEMENTS = 'ANNOUNCEMENTS';
const AUTO_SILENT = 'AUTO_SILENT';
const ADD_MOSQUE = 'ADD_MOSQUE';
const TASBIH_COUNTER = 'TASBIH_COUNTER';
const QIBLA_DIRECTION = 'QIBLA_DIRECTION';
const RAKAH_INFO = 'RAKAH_INFO';
const SPLASH_SCREEN = 'SPLASH_SCREEN';

//Registered Hindu
const REGISTERED_HINDU_HOME_STACK = 'REGISTERED_HINDU_HOME';
const REGISTERED_HINDU_DASHBOARD_STACK = 'REGISTERED_HINDU_DASHBOARD_STACK';

const RECITE_GITA = 'RECITE_GITA';
const FIND_TEMPLE = 'FIND_TEMPLE';
const VEG_DAYS = 'VEG_DAYS';
const VIEW_HINDU_CALANDER = 'VIEW_HINDU_CALANDER';
const HINDU_ANNOUNCEMENTS = 'HINDU_ANNOUNCEMENTS';
const HINDU_AUTO_SILENT = 'HINDU_AUTO_SILENT';
const ADD_TEMPLE = 'ADD_TEMPLE';

const GUEST_MUSLIM_HOME_STACK = 'Auth';
const IMAM_HOME_STACK = 'Auth';
const GUEST_HINDU_HOME_STACK = 'Auth';
const OTP_VERIFICATION = 'OTP_VERIFICATION';
//General User navigation constants
export {
  AUTH_STACK,
  SIGNUP,
  LOGIN,
  ENTER_AS_GUEST,
  OTP_VERIFICATION,
  SPLASH_SCREEN,
};

//Registered Muslim navigation constants
export {
  REGISTERED_MUSLIM_HOME_STACK,
  REGISTERED_MUSLIM_DASHBOARD_STACK,
  RECITE_QURAN,
  VIEW_CALANDER,
  FIND_MOSQUE,
  LEARN_NAMAZ,
  ACCOUNTABILITY,
  ANNOUNCEMENTS,
  AUTO_SILENT,
  ADD_MOSQUE,
  TASBIH_COUNTER,
  QIBLA_DIRECTION,
  RAKAH_INFO,
};

//Registered Hindu user navigation constants
export {
  REGISTERED_HINDU_HOME_STACK,
  REGISTERED_HINDU_DASHBOARD_STACK,
  RECITE_GITA,
  FIND_TEMPLE,
  VEG_DAYS,
  VIEW_HINDU_CALANDER,
  HINDU_ANNOUNCEMENTS,
  HINDU_AUTO_SILENT,
  ADD_TEMPLE,
};
