
//Notification categories

//announcements
const EID_NAMAZ='EID_NAMAZ'
const OTHER='OTHER'

const NAMAZ_ALERT='NAMAZ_ALERT'
const MOSQUE_CONSENSUS='MOSQUE_CONSENSUS'
const IMAM_CONSENSUS='IMAM_CONSENSUS'
const NEW_MOSQUE_ADDITION='NEW_MOSQUE_ADDITION'
const FUNERAL='FUNERAL_PRAYER'

const CATEGORIES={EID_NAMAZ,OTHER, NAMAZ_ALERT,MOSQUE_CONSENSUS,IMAM_CONSENSUS,NEW_MOSQUE_ADDITION, FUNERAL}
module.exports=CATEGORIES