/**
 * @author Nadir Hussain
 * @version 1.0
 */

//Common routes
const AUTH_STACK = 'AUTHENTICATION';
const LOGIN = 'LOGIN';
const SIGNUP = 'SIGNUP';
const ENTER_AS_GUEST = 'ENTER_AS_GUEST';
const SPLASH_SCREEN = 'SPLASH_SCREEN';
const SET_NEW_PASSWORD = 'SET_NEW_PASSWORD';
const OTP_VERIFICATION = 'OTP_VERIFICATION';
const NO_CONNECTION_SCREEN = 'NO_CONNECTION_SCREEN';
const ABOUT = 'ABOUT';
const GOOGLE_MAP = 'GOOGLE_MAP';
const GOOGLE_MAP_DIRECTIONS = 'GOOGLE_MAP_DIRECTIONS';

const HELP = 'HELP';

//Muslim Routes
const REGISTERED_MUSLIM_HOME_STACK = 'REGISTERED_MUSLIM_HOME';
const REGISTERED_MUSLIM_DASHBOARD_STACK = 'REGISTERED_MUSLIM_DASHBOARD_STACK';
const RECITE_QURAN = 'RECITE_QURAN';
const SURAH_RECITATION_AREA = 'SURAH_RECITATION_AREA';
const PARAH_RECITATION_AREA = 'PARAH_RECITATION_AREA';
const FIND_MOSQUE = 'FIND_MOSQUE';
const VIEW_CALANDER = 'VIEW_CALANDER';
const LEARN_NAMAZ = 'LEARN_NAMAZ';
const NAMAZ_PLAY_AREA = 'NAMAZ_PLAY_AREA';
const MUSLIM_USER_ANNOUNCEMENT_DETAILS = 'MUSLIM_USER_ANNOUNCEMENT_DETAILS';
const ACCOUNTABILITY = 'ACCOUNTABILITY';
const MUSLIM_ANNOUNCEMENTS = 'MUSLIM_ANNOUNCEMENTS';
const AUTO_SILENT = 'AUTO_SILENT';
const ADD_MOSQUE = 'ADD_MOSQUE';
const TASBIH_COUNTER = 'TASBIH_COUNTER';
const QIBLA_DIRECTION = 'QIBLA_DIRECTION';
const RAKAH_INFO = 'RAKAH_INFO';
const MAKE_ANNOUNCEMENT_SCREEN = 'MAKE_ANNOUNCEMENT_SCREEN';
const MUSLIM_VIEW_PROFILE = 'MUSLIM_VIEW_PROFILE';
const APPLY_AS_IMAM = 'APPLY_AS_IMAM';
const MUSLIM_DUAS = 'MUSLIM_DUAS';
const RECOMPENSE_GUIDELINES = 'RECOMPENSE_GUIDELINES';
const ALLAH_99_NAME = 'ALLAH_99_NAME';
const SET_PRAYER_TIMES = 'SET_PRAYER_TIMES';
const UPDATE_NAMAZ_TIMES_IN_MOSQUE = 'UPDATE_NAMAZ_TIMES_IN_MOSQUE';
const IMAM_CONSENSUS = 'IMAM_CONSENSUS';
const MOSQUE_CONSENSUS = 'MOSQUE_CONSENSUS';
const NEW_MOSQUE_ADDITION = 'NEW_MOSQUE_ADDITION';

//Hindu User Routes
const REGISTERED_HINDU_HOME_STACK = 'REGISTERED_HINDU_HOME';
const REGISTERED_HINDU_DASHBOARD_STACK = 'REGISTERED_HINDU_DASHBOARD_STACK';

const RECITE_GITA = 'RECITE_GITA';
const FIND_TEMPLE = 'FIND_TEMPLE';
const VEG_DAYS = 'VEG_DAYS';
const VIEW_HINDU_CALANDER = 'VIEW_HINDU_CALANDER';
const HINDU_ANNOUNCEMENTS = 'HINDU_ANNOUNCEMENTS';
const HINDU_USER_ANNOUNCEMENT_DETAILS = 'HINDU_USER_ANNOUNCEMENT_DETAILS';
const HINDU_USER_MAKE_ANNOUNCEMENT_SCREEN =
  'HINDU_USER_MAKE_ANNOUNCEMENT_SCREEN';
const HINDU_AUTO_SILENT = 'HINDU_AUTO_SILENT';
const ADD_TEMPLE = 'ADD_TEMPLE';
const TEMPLE_CONSENSUS = 'TEMPLE_CONSENSUS';
const NEW_TEMPLE_ADDITION = 'NEW_TEMPLE_ADDITION';
const HINDU_VIEW_PROFILE = 'HINDU_VIEW_PROFILE';
const GOOGLE_MAP_DIRECTIONS_FOR_HINDU_USERS =
  'GOOGLE_MAP_DIRECTIONS_FOR_HINDU_USERS';
const GITA_CHAPTER_RECITATION_AREA = 'GITA_CHAPTER_RECITATION_AREA';
const GITA_SUMMARY_RECITATION_AREA = 'GITA_SUMMARY_RECITATION_AREA';

//Muslim Tab Navigation
const MUSLIM_SETTINGS = 'Settings';
const MUSLIM_HOME = 'Home';
const MUSLIM_ALERTS = 'Alerts';
const MUSLIM_PRAYERS = 'Prayers';

//Hindu Tab Navigation
const HINDU_SETTINGS = 'HINDU_SETTINGS';
const HINDU_HOME = 'HINDU_HOME';
const HINDU_ALERTS = 'HINDU_ALERTS';
const HINDU_PRAYERS = 'HINDU_PRAYERS';

//prayers for hindus
const DAILY_PRAYER_INFO = 'DAILY_PRAYER_INFO';
const PRAYER_ITEMS_LIST = 'PRAYER_ITEMS_LIST';
const PRAYER_NOT_TODO = 'PRAYER_NOT_TODO';
const HINDU_MORNING_PRAYER = 'HINDU_MORNING_PRAYER';
const HINDU_EVENING_PRAYER = 'HINDU_EVENING_PRAYER';

//#region
export {
  AUTH_STACK,
  SIGNUP,
  LOGIN,
  ENTER_AS_GUEST,
  OTP_VERIFICATION,
  SPLASH_SCREEN,
  SET_NEW_PASSWORD,
  ABOUT,
  HELP,
  GOOGLE_MAP,
  GOOGLE_MAP_DIRECTIONS,
};
//#endregion

//#region Registered Muslim navigation constants
export {
  REGISTERED_MUSLIM_HOME_STACK,
  REGISTERED_MUSLIM_DASHBOARD_STACK,
  MUSLIM_ALERTS,
  MUSLIM_HOME,
  MUSLIM_SETTINGS,
  MUSLIM_PRAYERS,
  RECITE_QURAN,
  SURAH_RECITATION_AREA,
  PARAH_RECITATION_AREA,
  VIEW_CALANDER,
  FIND_MOSQUE,
  LEARN_NAMAZ,
  NAMAZ_PLAY_AREA,
  ACCOUNTABILITY,
  MUSLIM_ANNOUNCEMENTS,
  MAKE_ANNOUNCEMENT_SCREEN,
  MUSLIM_USER_ANNOUNCEMENT_DETAILS,
  AUTO_SILENT,
  ADD_MOSQUE,
  TASBIH_COUNTER,
  QIBLA_DIRECTION,
  RAKAH_INFO,
  MUSLIM_DUAS,
  ALLAH_99_NAME,
  RECOMPENSE_GUIDELINES,
  MUSLIM_VIEW_PROFILE,
  APPLY_AS_IMAM,
  IMAM_CONSENSUS,
  MOSQUE_CONSENSUS,
  NEW_MOSQUE_ADDITION,
  NO_CONNECTION_SCREEN,
  SET_PRAYER_TIMES,
  UPDATE_NAMAZ_TIMES_IN_MOSQUE, //For only imam
};
//#endregion

//Registered Hindu user navigation constants
export {
  REGISTERED_HINDU_HOME_STACK,
  REGISTERED_HINDU_DASHBOARD_STACK,
  HINDU_VIEW_PROFILE,
  RECITE_GITA,
  FIND_TEMPLE,
  VEG_DAYS,
  VIEW_HINDU_CALANDER,
  HINDU_ANNOUNCEMENTS,
  HINDU_USER_ANNOUNCEMENT_DETAILS,
  HINDU_AUTO_SILENT,
  ADD_TEMPLE,
  HINDU_SETTINGS,
  HINDU_HOME,
  HINDU_ALERTS,
  HINDU_PRAYERS,
  TEMPLE_CONSENSUS,
  NEW_TEMPLE_ADDITION,
  HINDU_USER_MAKE_ANNOUNCEMENT_SCREEN,
  GOOGLE_MAP_DIRECTIONS_FOR_HINDU_USERS,
  GITA_CHAPTER_RECITATION_AREA,
  GITA_SUMMARY_RECITATION_AREA,
  DAILY_PRAYER_INFO,
  PRAYER_ITEMS_LIST,
  PRAYER_NOT_TODO,
  HINDU_MORNING_PRAYER,
  HINDU_EVENING_PRAYER,
};
