
//Notification categories

//announcements
const FUNERAL_PRAYER='FUNERAL_PRAYER'
const OTHER='OTHER'

//const NAMAZ_ALERT='NAMAZ_ALERT'
const TEMPLE_CONSENSUS='TEMPLE_CONSENSUS'
const NEW_TEMPLE_ADDITION='NEW_TEMPLE_ADDITION'


const CATEGORIES={FUNERAL_PRAYER,OTHER,TEMPLE_CONSENSUS,IMAM_CONSENSUS,NEW_TEMPLE_ADDITION}
module.exports=CATEGORIES