const mongoose=require('mongoose')

const namazInfoSchema=mongoose.Schema({

    fajr:{
        totalRakah:{
            type:Number,
            default:4
        },
        farz:{
            type:Number,
            default:2
        },
        sunnah:{
            type:Number,
            default:2
        },
        nafl:{
            type:Number,
            default:0
        },
        vitr:{
            type:Number,
            default:0
        },
        takbirs:{
            type:Number,
            default:0
        },
    },

    zuhr:{
        totalRakah:{
            type:Number,
            default:12
        },
        farz:{
            type:Number,
            default:4
        },
        sunnah:{
            type:Number,
            default:6
        },
        nafl:{
            type:Number,
            default:2
        },
        vitr:{
            type:Number,
            default:0
        },
        takbirs:{
            type:Number,
            default:0
        },
    },
    asr:{
        totalRakah:{
            type:Number,
            default:8
        },
        farz:{
            type:Number,
            default:4
        },
        sunnah:{
            type:Number,
            default:4
        },
        nafl:{
            type:Number,
            default:0
        },
        vitr:{
            type:Number,
            default:0
        },
        takbirs:{
            type:Number,
            default:0
        },
    },
    maghrib:{
        totalRakah:{
            type:Number,
            default:7
        },
        farz:{
            type:Number,
            default:3
        },
        sunnah:{
            type:Number,
            default:2
        },
        nafl:{
            type:Number,
            default:2
        },
        vitr:{
            type:Number,
            default:0
        },
        takbirs:{
            type:Number,
            default:0
        },
    },
    isha:{
        totalRakah:{
            type:Number,
            default:19
        },
        farz:{
            type:Number,
            default:4
        },
        sunnah:{
            type:Number,
            default:6
        },
        nafl:{
            type:Number,
            default:4
        },
        vitr:{
            type:Number,
            default:3
        },
        takbirs:{
            type:Number,
            default:0
        },
    },
    jumma:{
        totalRakah:{
            type:Number,
            default:10
        },
        farz:{
            type:Number,
            default:2
        },
        sunnah:{
            type:Number,
            default:6
        },
        nafl:{
            type:Number,
            default:2
        },
        vitr:{
            type:Number,
            default:0
        },
        takbirs:{
            type:Number,
            default:0
        },
    },
    janaza:{
        totalRakah:{
            type:Number,
            default:4
        },
        farz:{
            type:Number,
            default:0
        },
        sunnah:{
            type:Number,
            default:0
        },
        nafl:{
            type:Number,
            default:0
        },
        vitr:{
            type:Number,
            default:0
        },
        takbirs:{      //4 takbirs
            type:Number,
            default:4
        },
    },
    eidNamaz:{
        totalRakah:{
            type:Number,
            default:2
        },
        farz:{
            type:Number,
            default:0
        },
        sunnah:{
            type:Number,
            default:6
        },
        nafl:{
            type:Number,
            default:4
        },
        vitr:{
            type:Number,
            default:3
        },
        takbirs:{      //Takbirs
            type:Number,
            default:12
        },
    },

})
 
module.exports=mongoose.model('NamazInfo', namazInfoSchema)